version: '3'
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - movie-book
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "3001:3001"
    networks: 
      - movie-book

networks: 
  movie-book:
    driver: bridge
