version: '3'
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - movie-book
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "3001:3001"
    networks: 
      - movie-book
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules

networks: 
  movie-book:
    driver: bridge
